### ISSUE TITLE
Example documentation not based in reality

### ISSUE THREAD

**Issue by georgegil** [RafaySystems/terraform-provider-rafay#35]
Documentation on creating a cloud credential (and frankly most resources) can do with some significant improvement

https://registry.terraform.io/providers/RafaySystems/rafay/latest/docs/resources/cloud_credential

telling me `credtype (Number)` is useless when I have no reference what those numbers mean. 

so I decided to look into the examples, lo and behold, it is completely different to a point I had to double check if this is actually the same provider:

https://github.com/RafaySystems/terraform-provider-rafay/tree/master/examples/resources/rafay_cloud_credential

Terrible.

**Comment by stephan-rafay** [comment]
Thanks for your feedback.
Please note that the released version of the provider is v0.0.19. The example documentation you were referring to is the master branch code, which is not released yet.

Please find the v0.0.19 code here:
https://github.com/RafaySystems/terraform-provider-rafay/tree/v0.0.19

Thank you again for bringing this to our attention. We are working to find a solution to avoid this type of confusion in the future.
